name: Continuous Integration
on: [push]

jobs:
  checkout:
    name: Checkout
    runs-on: self-hosted
    steps:
      - name: Git checkout
        uses: actions/checkout@v2.1.1
      - name: Composer Install
        uses: nick-zh/composer@php7.4
        with:
          action: 'install'
      - name: Initialize (temp)
        uses: nick-zh/composer@php7.4
        with:
          action: 'db:init'
  dependencies:
    name: Install dependencies
    runs-on: self-hosted
    steps:
      - name: Composer Install
        uses: nick-zh/composer@php7.4
        with:
          action: 'install'
  initialize:
    name: Composer initialize
    runs-on: self-hosted
    steps:
      - name: Initialize (temp)
        uses: nick-zh/composer@php7.4
        with:
          action: 'db:init'